# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://cornhacks.com"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: ""

# Let people connect & engage with you through social media.
social:
  twitter_handle: "CornHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "CornHacks"
  description: "Collegiate Hackathon at the University of Nebraska-Lincoln"
  image:       "images/logo.png"

# Event information.
event:
  name:        "CornHacks"
  description: "Undergraduate hackathon at UNL"
  date:        "January 18 - 19, 2020"
  location:    "Johnny Carson Center for Emerging Media Arts"

  trust_badge:
    year:   "2019"  # season year
    region: "na"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Register"
        href: "https://docs.google.com/forms/d/e/1FAIpQLSeAkHrIt3hNqLuUDzsBbOl6Tz7_IJFRIHgwksdrvCOlVuWbug/viewform?usp=sf_link"
      - text: "Sponsor"
        href: "mailto:cornhacks@gmail.com"

  hero2:
    links:
      - text: "View on DevPost"
        href: "https://cornhacks-2020.devpost.com"

  about:
    description: >
      CornHacks aims to bring some of the most talented developers from around the Midwest to join in a weekend full of hacking.

      Hosted at the University of Nebraska-Lincoln, over 100 participants will code all day and night to be judged by industry professionals and compete for several prizes.

  # Info Sections
  info:
    sections:
      - image: "images/icons8-literature.png"
        title: "LEARN."
        description: >
          Strengthen your skills. Learn a new technology. Get help from experts.
      - image: "images/icons8-hammer.png"
        title: "BUILD."
        description: >
          Work as a team on an innovative idea.
      - image: "images/icons8-share.png"
        title: "SHARE."
        description: >
          Present your hack. Win a prize.

  # Sponsorship Sections
  sponsorship:
    gold:
      - image: "images/Builder_Trend_0.jpg"
      - image: "images/DMSI_Resize.png"
      - image: "images/SandhillsGlobal-Stacked_Logo_2Color_1_2_15.jpg"
    silver:
      - image: "images/TravefyResize.png"

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software and hardware hacks over the weekend. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing! Admission is free and includes meals, drinks, snacks, workshops, swag, and a memorable learning experience!
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only undergraduate students who are at least 18 years old are able to attend.
    - question: "What is the schedule?"
      answer: >
        [View the full event schedule here.](https://drive.google.com/file/d/1N7PwgYFuP-YxnU4cC6eSXdI8NuSj9Dco/view?usp=sharing)
    - question: "Where is the event?"
      answer: >
       [Johnny Carson Center for Emerging Media Arts](https://goo.gl/maps/45upVWupAFW9bNvf8)
    - question: "Will there be prizes?"
      answer: >
        Expect more than $3,500 in prizes!
    # - question: "What is Major League Hacking?"
    #   answer: >
    #     Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
    #     They work with over 200 Member Events and empower over 70,000 students every year.
    - question: "What if I don't have a team?"
      answer: >
        If you don’t have a team now, that’s okay! We’ll have team formation and events geared towards helping you find people to work with. Teams can have up to four students.
    - question: "What will I eat?"
      answer: >
        We’ll provide food for all meals. If you have dietary restrictions, we’ll try our best to accommodate them. We’ll also have snacks throughout the hackathon.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. You can find [UNL's policy here](https://studentconduct.unl.edu/student-code-conduct).

    # - question: "Is there a code of conduct?"
      # answer: >
      #   Yes there is. You can find the [MLH's policy here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf) and [UNL's policy here](https://studentconduct.unl.edu/student-code-conduct).
    - question: "What if this is my first hackathon?"
      answer: >
        That's great! The most important thing is that you're there; have fun, and learn something. Go ahead and register to make the most out of the experience. It's completely free, so there's nothing to lose!

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
