# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://cornhacks.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: ""

# Let people connect & engage with you through social media.
social:
  twitter_handle: "CornHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "CornHacks"
  description: "Collegiate Hackathon at the University of Nebraska-Lincoln"
  image:       "images/logo.png"

# Event information.
event:
  name:        "CornHacks"
  description: "Hackathon"
  date:        "February 17-18, 2018"
  location:    "Lincoln, NE, United States"

  trust_badge:
    year:   "2018"  # season year
    region: "na"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "5924f24c2e8737c9c7f19e29c5159a4e576b701b8a9a182b84aa4d32053f1c24"
          redirect_uri: "https://cornhacks.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:cornhacks2018@gmail.com"

  about:
    description: >
      CornHacks aims to bring some of the most talented developers from around the Midwest to join in a weekend full of hacking. 

      Hosted at the University of Nebraska-Lincoln, over 100 participants will code all day and night to be judged by industry professionals and compete for several prizes.

  # Info Sections
  info:
    sections:
      - image: "images/icons8-literature.png"
        title: "LEARN."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/icons8-hammer.png"
        title: "BUILD."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/icons8-share.png"
        title: "SHARE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software and hardware hacks over 24 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing! Admission is free and includes meals, drinks, snacks, overnight hosting, workshops, swag, and a memorable learning experience!
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at Kauffman Hall on the University of Nebraska-Lincoln's campus. The address is 630 N 15th St, Lincoln, NE 68508.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        They work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "What if I don't have a team?"
      answer: >
        If you don’t have a team now, that’s okay! We’ll have team formation and events geared towards helping you find people to work with.
    - question: "What will I eat?"
      answer: >
        We’ll provide food for all meals from Saturday’s breakfast to Sunday’s lunch. If you have dietary restrictions, we’ll try our best to accommodate them. We’ll also have snacks throughout the hackathon.

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
